config/routes.rb
Rails.application.routes.draw do
  resources :artifacts
  resources :projects
  devise_for :users, :controllers => { :registrations => 'registrations' }
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artifact.rb
class Artifact < ApplicationRecord
  belongs_to :project
  attr_accessor :upload

  MAX_FILESIZE = 10.megabytes
  validates_presence_of :name, :upload
  validates_uniqueness_of :name
  validate :uploaded_file_size
  def uploaded_file_size
    if upload
      errors.add(:upload, "File size must be less than #{self.class::MAX_FILESIZE}") unless upload.size <= self.class::MAX_FILESIZE

    end

  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
    attr_accessor :card_number, :card_cvv, :card_expires_month, :card_expires_year
    belongs_to :user
     def self.month_options
        Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1]}
    end
    def self.year_options
        (Date.today.year..(Date.today.year+10)).to_a
    end

    def process_payment
        customer = Stripe::Customer.create email: email, card: token
        Stripe::PaymentIntent.create customer: customer.id,amount: 1000,description: 'Premium',currency: 'usd'
    end

end

app/models/plan.rb
class Plan
    PLANS = [:free, :premium]

    def self.options
        PLANS.map { |plan| [plan.capitalize, plan] }
    end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :artifacts, dependent: :destroy


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :validatable

  has_one :payment
  accepts_nested_attributes_for :payment


  def is_admin?
    is_admin

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:create, :destroy]
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:plan, :organization])
    devise_parameter_sanitizer.permit(:account_update, keys: [:plan, :organization])
  end

end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: %i[ show edit update destroy ]

  # GET /artifacts or /artifacts.json
  def index
    @artifacts = Artifact.all
  end

  # GET /artifacts/1 or /artifacts/1.json
  def show
  end

  # GET /artifacts/new
  def new
    @artifact = Artifact.new
  end

  # GET /artifacts/1/edit
  def edit
  end

  # POST /artifacts or /artifacts.json
  def create
    @artifact = Artifact.new(artifact_params)

    respond_to do |format|
      if @artifact.save
        format.html { redirect_to artifact_url(@artifact), notice: "Artifact was successfully created." }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artifacts/1 or /artifacts/1.json
  def update
    respond_to do |format|
      if @artifact.update(artifact_params)
        format.html { redirect_to artifact_url(@artifact), notice: "Artifact was successfully updated." }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1 or /artifacts/1.json
  def destroy
    @artifact.destroy

    respond_to do |format|
      format.html { redirect_to artifacts_url, notice: "Artifact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artifact_params
      params.require(:artifact).permit(:name, :key, :project_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :details, :expected_completion_date, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def create
        build_resource(sign_up_params)
        resource.class.transaction do
            resource.save
            yield resource if block_given?
            if resource.persisted?
                if @user.plan=="premium"
                    @payment = Payment.new({ email: params["user"]["email"],
                    token: params[:payment]["token"], user_id: resource.id })
                    flash[:error] = "Please check registration errors" unless @payment.valid?
                    
                    begin
                        @payment.process_payment
                        @payment.save 
                    rescue Exception => e
                        flash[:error] = e.message
                        resource.destroy
                        puts 'Payment failed'
                        render :new and return
                    end
                end
                if resource.active_for_authentication?
                    set_flash_message :notice, :signed_up if is_flashing_format?
                    sign_up(resource_name, resource)
                    respond_with resource, location: after_sign_up_path_for(resource)
                else
                    set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
                    expire_data_after_sign_in!
                    respond_with resource, location: after_inactive_sign_up_path_for(resource)
                end

            else
                clean_up_passwords resource
                set_minimum_password_length
                respond_with resource
            end
        end
    end

    protected
def configure_permitted_parameters1
  devise_parameter_sanitizer.permit(:sign_up, keys: [:payment])
  devise_parameter_sanitizer.permit(:sign_up, keys: [:plan, :organization])
    devise_parameter_sanitizer.permit(:account_update, keys: [:plan, :organization])
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/artifacts/_form.html.erb
<%= form_with(model: artifact) do |form| %>
  <% if artifact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artifact.errors.count, "error") %> prohibited this artifact from being saved:</h2>

      <ul>
        <% artifact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :key %>
    <%= form.text_field :key %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artifacts/edit.html.erb
<h1>Editing Artifact</h1>

<%= render 'form', artifact: @artifact %>

<%= link_to 'Show', @artifact %> |
<%= link_to 'Back', artifacts_path %>

app/views/artifacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artifacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Key</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artifacts.each do |artifact| %>
      <tr>
        <td><%= artifact.name %></td>
        <td><%= artifact.key %></td>
        <td><%= artifact.project_id %></td>
        <td><%= link_to 'Show', artifact %></td>
        <td><%= link_to 'Edit', edit_artifact_path(artifact) %></td>
        <td><%= link_to 'Destroy', artifact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artifact', new_artifact_path %>

app/views/artifacts/new.html.erb
<h1>New Artifact</h1>

<%= render 'form', artifact: @artifact %>

<%= link_to 'Back', artifacts_path %>

app/views/artifacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artifact.name %>
</p>

<p>
  <strong>Key:</strong>
  <%= @artifact.key %>
</p>

<p>
  <strong>Project:</strong>
  <%= @artifact.project_id %>
</p>

<%= link_to 'Edit', edit_artifact_path(@artifact) %> |
<%= link_to 'Back', artifacts_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.erb
 <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; Your Website</small>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <%= link_to ("<i class='fa fa-rocket'></i> " +'Project Management App').html_safe, root_path, class: "navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
       <% if current_user %>
        <li class="nav-item">
        <%= link_to "Projects", projects_path, class:"nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Projects
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Projects", projects_path, class:"dropdown-item"%>
            <%= link_to "createproject", new_project_path, class:"dropdown-item"%>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Artifacts
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Artifacts", artifacts_path, class:"dropdown-item"%>
            <%= link_to "createArtifacts", new_artifact_path, class:"dropdown-item"%>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-power-off"></i>Logout
          <% end %>
        </li>
    <% else %>
      <li class="col-md-4 pull-right nav-item">
        <%= link_to 'Login', new_user_session_path, class:"btn btn-outline-success " %></li>
      </li>
    <% end %>
   </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaasprojectApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= bootstrap_icon "check", width: 5, height: 5, fill: "blue" %>
    
  </head>

  <body class="d-flex flex-column"> 
    <%=render 'layouts/navigation' %>
    <div id="page-content">
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <p><%= notice %></p>
        <p><%= alert %></p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      </div>
      <%= yield %>
    </div>
    <%=render 'layouts/footer' %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => "form-horizontal project" } do |f| %>

  <% if @project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :details, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :details, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :expected_completion_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
    <%= f.date_field :expected_completion_date, min: 0.days.ago,:class => 'form-control' %>
    </div>
   
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:details) %></th>
      <th><%= model_class.human_attribute_name(:expected_completion_date) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, project_path(project) %></td>
        <td><%= project.title %></td>
        <td><%= project.details %></td>
        <td><%= project.expected_completion_date %></td>
        <td><%= project.user_id %></td>
        <td><%=l project.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      project_path(project), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @project.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt>
  <dd><%= @project.details %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expected_completion_date) %>:</strong></dt>
  <dd><%= @project.expected_completion_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @project.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>